import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { LockKeyhole, PackagePlus } from 'lucide-react';
import { api } from '../../lib/api';
import { Button } from '../../components/ui/Button';
import type { Product, Supplier } from '../../lib/types';

export const IncomingPage: React.FC = () => {
  const [authorized, setAuthorized] = useState(false);
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [form, setForm] = useState({ productId: '', quantity: '1', unitPrice: '', notes: '' });
  const queryClient = useQueryClient();
  const { data: products = [] } = useQuery<Product[]>({ queryKey: ['products'], queryFn: () => api.get('/products', { params: { limit: 200, status: 'ACTIVE' } }).then((res) => res.data.data), enabled: authorized });
  const { data: suppliers = [] } = useQuery<Supplier[]>({ queryKey: ['suppliers'], queryFn: () => api.get('/suppliers', { params: { limit: 100 } }).then((res) => res.data.data), enabled: authorized });
  const { data: me } = useQuery<{ email: string }>({ queryKey: ['me'], queryFn: () => api.get('/auth/me').then((res) => res.data.data) });
  const receive = useMutation({ mutationFn: () => api.post('/inventory/stock-in', { productId: form.productId, quantity: Number(form.quantity), unitPrice: Number(form.unitPrice) || undefined, notes: form.notes }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['products'] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }); setForm({ productId: '', quantity: '1', unitPrice: '', notes: '' }); } });
  const unlock = async () => { try { await api.post('/auth/login', { email: me?.email, password }); setAuthorized(true); setError(''); } catch { setError('Incorrect administrator password.'); } };
  if (!authorized) return <div className="mx-auto max-w-md rounded-3xl border border-white/80 bg-white/85 p-8 text-center shadow-2xl shadow-slate-300/40"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-3xl bg-sky-100 text-sky-700"><LockKeyhole /></span><h1 className="mt-5 text-2xl font-bold">Admin approval required</h1><p className="mt-2 text-sm text-slate-500">Confirm your administrator password to receive stock.</p><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && unlock()} placeholder="Admin password" className="mt-6 h-14 w-full rounded-2xl border-0 bg-slate-100 px-4 outline-none focus:ring-2 focus:ring-sky-300" /><Button className="mt-4 h-14 w-full rounded-2xl bg-sky-600" onClick={unlock}>Unlock receiving</Button>{error && <p className="mt-3 text-sm font-semibold text-red-600">{error}</p>}</div>;
  return <div className="mx-auto max-w-3xl space-y-6"><header><p className="text-sm font-semibold uppercase tracking-widest text-sky-700">Incoming goods</p><h1 className="text-3xl font-bold">Receive stock</h1></header><form onSubmit={(event) => { event.preventDefault(); receive.mutate(); }} className="grid gap-4 rounded-3xl border border-white/80 bg-white/85 p-6 shadow-xl shadow-slate-200/50 sm:grid-cols-2"><div className="sm:col-span-2"><label className="text-sm font-semibold">Product</label><select required value={form.productId} onChange={(event) => setForm({ ...form, productId: event.target.value })} className="mt-2 h-12 w-full rounded-2xl border-0 bg-slate-100 px-4"><option value="">Select product</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name} · {product.stockQuantity} in stock</option>)}</select></div><div><label className="text-sm font-semibold">Quantity</label><input required type="number" min="1" value={form.quantity} onChange={(event) => setForm({ ...form, quantity: event.target.value })} className="mt-2 h-12 w-full rounded-2xl border-0 bg-slate-100 px-4" /></div><div><label className="text-sm font-semibold">Cost price</label><input type="number" min="0" step="0.01" value={form.unitPrice} onChange={(event) => setForm({ ...form, unitPrice: event.target.value })} className="mt-2 h-12 w-full rounded-2xl border-0 bg-slate-100 px-4" /></div><div><label className="text-sm font-semibold">Supplier</label><select className="mt-2 h-12 w-full rounded-2xl border-0 bg-slate-100 px-4"><option value="">Optional supplier</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></div><div><label className="text-sm font-semibold">Date received</label><input type="date" defaultValue={new Date().toISOString().slice(0, 10)} className="mt-2 h-12 w-full rounded-2xl border-0 bg-slate-100 px-4" /></div><div className="sm:col-span-2"><label className="text-sm font-semibold">Notes</label><textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} className="mt-2 min-h-24 w-full rounded-2xl border-0 bg-slate-100 p-4" placeholder="Delivery notes" /></div><Button type="submit" className="h-14 rounded-2xl bg-sky-600 sm:col-span-2" loading={receive.isPending}><PackagePlus className="mr-2" />Receive stock</Button>{receive.isSuccess && <p className="text-sm font-semibold text-emerald-700 sm:col-span-2">Inventory updated successfully.</p>}</form></div>;
};
